import Head from "next/head";
import { ReactNode } from "react";
import Header from "./Header";

function Layout({
  children,
  pageTitle,
}: {
  children: ReactNode;
  pageTitle: string;
}) {
  return (
    <>
      <Head>
        <title>The Good Corner - {pageTitle}</title>
        <meta name="description" content="Generated by Create Next App" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="main-content">{children}</main>
    </>
  );
}

export default Layout;
