GET http://localhost:4000/ads

###

GET http://localhost:4000/ads/4

###

POST http://localhost:4000/ads
Content-Type: application/json

 {
    "title": "Porte magazine",
    "description":
      "Porte magasine",
    "owner": "M. Fernand",
    "price": 45,
    "picture": "/images/porte-magazine.webp",
    "location": "Lilles",
    "category": 2,
    "tags": [{"id": 3}, {"id": 4}]
  }

### 

DELETE http://localhost:4000/ads/9

###

PUT http://localhost:4000/ads/10
Content-Type: application/json

{
  "picture": "/images/table.webp"
}