GET http://localhost:4000/ads

###

GET http://localhost:4000/ads/4

###

POST http://localhost:4000/ads
Content-Type: application/json

 {
    "title": "iPod",
    "description":
      "My iPod is blue and works fine",
    "owner": "anais@gmail.com",
    "price": 50,
    "location": "Toulouse"
  }

### 

DELETE http://localhost:4000/ads/3

###

PATCH http://localhost:4000/ads/1
Content-Type: application/json

{
  "title" : "Jeans troués"
}