GET http://localhost:4000/tags

###

GET http://localhost:4000/tags/4

###

POST http://localhost:4000/tags
Content-Type: application/json

 {
    "Name" : "Vêtement"
  }

### 

DELETE http://localhost:4000/tags/4

###

PUT http://localhost:4000/tags/1
Content-Type: application/json

{
  "name" : "Téléphone"
}